image: python:3.9.1-alpine3.12

stages:
  - lint
  - unit-test
  # - integration-test

pylint:
  stage: lint
  tags:
    - docker-gcc
  image: python:3
  before_script:
    - pip install pylint_gitlab
  script:
    - pip install -r requirements.txt
    - pylint --exit-zero --output-format=text $(find ./src -type f -name "*.py") | tee /tmp/pylint.txt
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find ./src -type f -name "*.py") > codeclimate.json
  artifacts:
    reports:
      codequality: codeclimate.json
    when: always

unit-test:
  stage: unit-test
  tags:
    - docker-gcc
  image: python:3
  script:
    - pip install pytest pytest-cov
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# integration-test:
#   stage: integration-test
#   tags:
#     - docker-gcc
#   image: python:3.7-slim
#   script:
#     - pip install -r requirements.txt
#     - pytest
#   artifacts:
#     reports:
#       codequality: codeclimate.json
#     when: always