heat_template_version: 2018-03-02

description: >
  security group setup for security plus environment.

parameters:
  ports:
    type: comma_delimited_list
    label: ports
    default: "3389,22"
  directions:
    type: comma_delimited_list
    label: direction for rule
    default: "ingress,egress"
  protocols:
    type: comma_delimited_list
    label: protocols for rule
    default: "tcp,udp"
  guac_server_subnet:
    type: string
    label: guac_server_subnet
    default: 10.100.1.0/24


resources:
  secplus.guacamole.security.group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow SSH and RDP Access from Guacamole Server
      name: secplus.guacamole.security.group
      rules:
        repeat:
          for_each:
            <%port%>: { get_param: ports }
          template:
            remote_ip_prefix: { get_param: guac_server_subnet }
            direction: ingress
            protocol: tcp
            port_range_min: <%port%>
            port_range_max: <%port%>

  secplus.any.security.group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow Any 
      name: secplus.any.security.group
      rules:
        repeat:
          for_each:
            <%protocol%>: { get_param: protocols }
            <%direction%>: { get_param: directions }
          template:
            remote_ip_prefix: 0.0.0.0/0
            protocol: <%protocol%>
            direction: <%direction%>
            port_range_min: 1
            port_range_max: 65535
